// Shared style objects for Admin Mode. Kept as CSSProperties so they sit
// next to the rest of the terminal (which doesn't use a CSS-in-JS lib).
// Animations live in admin.css — these are static.

import type { CSSProperties } from 'react';

/** Tiny coloured status dot used inline next to a tile hint. Lives outside
 *  `adminStyles` because Record<string, CSSProperties> can't hold a factory. */
export function tileStatusDotStyle(color: string): CSSProperties {
  return {
    display: 'inline-block',
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: color,
    marginRight: 6,
    verticalAlign: 'middle',
  };
}

export const adminStyles: Record<string, CSSProperties> = {
  shell: {
    position: 'absolute',
    inset: 0,
    background: 'var(--bg)',
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    overflow: 'hidden',
  },

  // ─── Top bar (dark brown, slim) ────────────────────────────────────────
  topbar: {
    height: 56,
    flexShrink: 0,
    background: 'var(--sidebar)',
    color: '#e8ddd0',
    display: 'grid',
    gridTemplateColumns: '1fr auto 1fr',
    alignItems: 'center',
    padding: '0 16px',
    gap: 16,
    borderBottom: '1px solid rgba(0,0,0,0.2)',
  },
  topbarLeft: { display: 'flex', alignItems: 'center', gap: 12, height: '100%' },
  topbarCenter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
    minWidth: 0,
    overflow: 'hidden',
  },
  topbarRight: { display: 'flex', alignItems: 'center', gap: 12, justifyContent: 'flex-end', height: '100%' },
  backBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '7px 12px 7px 8px',
    borderRadius: 8,
    background: 'rgba(232,221,208,0.06)',
    color: '#e8ddd0',
    border: '1px solid rgba(232,221,208,0.12)',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
    minHeight: 38,
    fontFamily: 'inherit',
  },
  crumbGroup: { display: 'inline-flex', alignItems: 'center', minWidth: 0 },
  crumb: {
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: '0.01em',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '32ch',
    transition: 'color 180ms cubic-bezier(0.22, 1, 0.36, 1)',
  },
  crumbMuted: { color: 'rgba(232,221,208,0.55)' },
  crumbActive: { color: '#f0e0c0' },
  crumbSep: {
    fontSize: 13,
    fontWeight: 400,
    color: 'rgba(232,221,208,0.30)',
    margin: '0 10px',
    userSelect: 'none',
  },
  searchPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 12px 6px 10px',
    borderRadius: 8,
    background: 'rgba(232,221,208,0.08)',
    color: 'rgba(232,221,208,0.85)',
    border: '1px solid rgba(232,221,208,0.12)',
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    fontFamily: 'inherit',
    minHeight: 34,
  },
  userPill: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    paddingLeft: 14,
    borderLeft: '1px solid rgba(232,221,208,0.12)',
    height: '100%',
  },
  userInitials: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #6b5e54, #2c2420)',
    color: '#e8ddd0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 600,
    fontSize: 11,
    border: '1px solid rgba(232,221,208,0.12)',
  },
  userText: { display: 'flex', flexDirection: 'column', lineHeight: 1.15 },
  userName: { fontSize: 12, fontWeight: 600, color: '#fff', whiteSpace: 'nowrap' },
  userRole: {
    fontSize: 9,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: 'rgba(232,221,208,0.55)',
    marginTop: 1,
  },

  // The principal-page root view (narrative / palette entry / section row)
  // is laid out entirely via admin.css classes — see .admin-launcher-root,
  // .admin-narrative*, .admin-palette-entry*, .admin-section-row,
  // .admin-mini-card*. Keeping the structural rules in CSS lets the layout
  // breathe via container-query units instead of inline pixel math.

  // ─── Breadcrumb header (replaces greeting while drilled into a section) ─
  crumbBlock: {
    padding: '20px 32px 8px',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 14,
  },
  crumbBack: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '7px 12px 7px 8px',
    borderRadius: 8,
    background: 'var(--bg2)',
    color: 'var(--text1)',
    border: '1px solid var(--border)',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: 'inherit',
    minHeight: 36,
  },
  crumbTrail: {
    display: 'inline-flex',
    alignItems: 'baseline',
    gap: 8,
    minWidth: 0,
  },
  crumbRoot: {
    fontSize: 11,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: 'var(--text3)',
    fontWeight: 700,
  },
  crumbDot: {
    color: 'var(--text3)',
    fontSize: 12,
  },
  crumbCurrent: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    fontWeight: 600,
    color: 'var(--text1)',
    letterSpacing: '-0.005em',
  },
  // ─── Launcher body (drill-down view only — root uses admin.css classes) ─
  body: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    padding: '6px 32px 24px',
  },
  section: {
    marginTop: 22,
  },
  sectionLabel: {
    fontSize: 10,
    letterSpacing: '0.32em',
    textTransform: 'uppercase',
    color: 'var(--text3)',
    fontWeight: 700,
    padding: '0 4px 12px',
  },
  tileGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 14,
  },

  // ─── Tile ───────────────────────────────────────────────────────────────
  // Tiles stretch to fill their grid cell. Content sits at the BOTTOM of
  // the card with the icon pushed to the top via a flex spacer — a
  // Launchpad-meets-restaurant-menu rhythm that survives any cell size:
  // small cards stay legible, big cards don't look top-heavy.
  tile: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: '20px 22px 20px',
    background: 'var(--bg2)',
    border: '1px solid var(--border)',
    borderRadius: 16,
    minHeight: 138,
    width: '100%',
    height: '100%',
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
    color: 'var(--text1)',
    boxShadow: '0 1px 0 rgba(44,36,32,0.02), 0 6px 18px rgba(44,36,32,0.03)',
    overflow: 'hidden',
  },
  tileSpacer: {
    flex: 1,
    minHeight: 6,
  },
  tileNumber: {
    position: 'absolute',
    top: 14,
    right: 16,
    fontFamily: 'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--text3)',
    letterSpacing: 0,
  },
  tileIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 22,
    marginBottom: 4,
    color: '#2c2420',
  },
  tileTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 17,
    fontWeight: 600,
    color: 'var(--text1)',
    lineHeight: 1.2,
  },
  tileHint: {
    fontSize: 12,
    color: 'var(--text2)',
    lineHeight: 1.35,
  },

  // ─── Live signal on section cards (principal launcher) ─────────────────
  // Replaces the static "{n} actions" hint with a glanceable status line:
  // small status dot, a Playfair headline carrying the lead value, then a
  // muted secondary line in DM Sans. The whole block sits flush at the
  // bottom of the tile so card heights stay aligned across the grid.
  // All font-size / spacing values clamp with viewport so the launcher's
  // live blocks scale from a 1280px laptop to a 4K display without going
  // postage-stamp on the large end. The .admin-mini-card-live class in
  // admin.css owns the outer slot.
  // Font-size / spacing values clamp with viewport but stay restrained
  // so the launcher's live blocks scale slightly at 4K without taking
  // over the card. The .admin-mini-card-live class in admin.css owns
  // the outer slot.
  liveBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'clamp(2px, 0.15vw, 4px)',
    minWidth: 0,
  },
  liveHeadlineRow: {
    display: 'inline-flex',
    alignItems: 'baseline',
    gap: 'clamp(8px, 0.5vw, 12px)',
    minWidth: 0,
  },
  liveDot: {
    display: 'inline-block',
    width: 'clamp(7px, 0.42vw, 9px)',
    height: 'clamp(7px, 0.42vw, 9px)',
    borderRadius: '50%',
    flexShrink: 0,
    transform: 'translateY(-1px)',
  },
  liveHeadline: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 'clamp(15px, 0.95vw, 19px)',
    fontWeight: 600,
    color: 'var(--text1)',
    lineHeight: 1.1,
    fontVariantNumeric: 'tabular-nums',
    letterSpacing: '-0.005em',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    minWidth: 0,
  },
  liveSecondary: {
    fontSize: 'clamp(11px, 0.7vw, 13px)',
    color: 'var(--text2)',
    lineHeight: 1.35,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    // Align under the headline text past the dot + gap, using the same
    // clamps so the offset tracks with the dot size.
    paddingLeft: 'calc(clamp(7px, 0.42vw, 9px) + clamp(8px, 0.5vw, 12px))',
  },
  liveSecondaryAlert: {
    fontSize: 'clamp(11px, 0.7vw, 13px)',
    color: 'var(--red)',
    fontWeight: 600,
    lineHeight: 1.35,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    paddingLeft: 'calc(clamp(7px, 0.42vw, 9px) + clamp(8px, 0.5vw, 12px))',
  },
  liveMuted: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 'clamp(13px, 0.85vw, 16px)',
    fontWeight: 500,
    color: 'var(--text2)',
    lineHeight: 1.2,
    letterSpacing: '-0.005em',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  liveSkeletonHead: {
    height: 'clamp(16px, 0.95vw, 20px)',
    width: '62%',
    borderRadius: 4,
    background:
      'linear-gradient(90deg, rgba(216,205,184,0.30) 0%, rgba(216,205,184,0.55) 50%, rgba(216,205,184,0.30) 100%)',
    backgroundSize: '200% 100%',
  },
  liveSkeletonSub: {
    height: 'clamp(10px, 0.65vw, 13px)',
    width: '44%',
    borderRadius: 3,
    marginTop: 'clamp(7px, 0.4vw, 10px)',
    background:
      'linear-gradient(90deg, rgba(216,205,184,0.22) 0%, rgba(216,205,184,0.45) 50%, rgba(216,205,184,0.22) 100%)',
    backgroundSize: '200% 100%',
  },
  liveLocked: {
    fontSize: 'clamp(11px, 0.65vw, 12px)',
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: 'var(--text3)',
    fontWeight: 700,
  },
  // ─── Hint footer ────────────────────────────────────────────────────────
  hintBar: {
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 18,
    padding: '10px 28px',
    borderTop: '1px solid var(--border)',
    background: 'var(--bg2)',
    fontSize: 12,
    color: 'var(--text2)',
    overflowX: 'auto',
  },
  hintItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    whiteSpace: 'nowrap',
  },

  // ─── Command palette ────────────────────────────────────────────────────
  paletteScrim: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(44,36,32,0.34)',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingTop: '12vh',
    zIndex: 90,
  },
  palette: {
    width: 560,
    maxWidth: 'calc(100% - 32px)',
    background: 'var(--bg2)',
    borderRadius: 14,
    boxShadow: '0 24px 64px rgba(0,0,0,0.32)',
    border: '1px solid var(--border)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  paletteInputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '14px 16px',
    borderBottom: '1px solid var(--border)',
  },
  paletteInput: {
    flex: 1,
    border: 'none',
    background: 'transparent',
    color: 'var(--text1)',
    fontSize: 15,
    fontFamily: 'inherit',
    outline: 'none',
    minWidth: 0,
  },
  paletteEscHint: {
    fontSize: 11,
    color: 'var(--text3)',
    flexShrink: 0,
  },
  paletteList: {
    maxHeight: 360,
    overflowY: 'auto',
    padding: '6px 0',
  },
  paletteRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 16px',
    cursor: 'pointer',
    color: 'var(--text1)',
  },
  paletteIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    color: '#2c2420',
    flexShrink: 0,
  },
  paletteRowText: { display: 'flex', flexDirection: 'column', minWidth: 0, flex: 1 },
  paletteRowTitle: { fontSize: 13, fontWeight: 600, color: 'var(--text1)' },
  paletteRowMeta: {
    fontSize: 11,
    color: 'var(--text3)',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  paletteRowKbd: {
    fontFamily: 'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
    fontSize: 11,
    color: 'var(--text3)',
    flexShrink: 0,
  },
  paletteEmpty: {
    padding: '28px 16px',
    textAlign: 'center',
    color: 'var(--text3)',
    fontSize: 13,
  },

  // ─── Cash movement picker (intermediate Income/Expense choice) ─────────
  pickerScrim: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(44,36,32,0.42)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 75,
    padding: 24,
  },
  pickerCard: {
    width: 420,
    maxWidth: '100%',
    background: 'var(--bg2)',
    borderRadius: 14,
    boxShadow: '0 24px 64px rgba(0,0,0,0.32)',
    border: '1px solid var(--border)',
    overflow: 'hidden',
  },
  pickerHead: { padding: '20px 22px 14px', borderBottom: '1px solid var(--border)' },
  pickerTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 20,
    fontWeight: 600,
    color: 'var(--text1)',
    margin: 0,
  },
  pickerSub: { fontSize: 12, color: 'var(--text2)', marginTop: 4, lineHeight: 1.4 },
  pickerGrid: {
    padding: '18px 22px 22px',
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: 12,
  },

  // ─── Admin view shell (real sub-views: ShiftAudit, CashLog, etc.) ──────
  viewShell: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
  },
  viewHead: {
    padding: '20px 32px 14px',
    borderBottom: '1px solid var(--border)',
    display: 'flex',
    alignItems: 'flex-start',
    gap: 14,
    flexShrink: 0,
  },
  viewTitleBlock: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minWidth: 0,
  },
  viewTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 24,
    fontWeight: 600,
    color: 'var(--text1)',
    margin: 0,
    letterSpacing: '-0.005em',
    lineHeight: 1.2,
  },
  viewSubtitle: {
    fontSize: 13,
    color: 'var(--text2)',
    marginTop: 4,
    lineHeight: 1.4,
  },
  viewActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  viewBody: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    padding: '20px 32px 32px',
  },

  // KPI strip shared by admin views with summary metrics on top.
  kpiRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: 12,
    marginBottom: 20,
  },
  kpiCard: {
    background: 'var(--bg2)',
    border: '1px solid var(--border)',
    borderRadius: 10,
    padding: '14px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  kpiLabel: {
    fontSize: 10,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: 'var(--text3)',
    fontWeight: 700,
  },
  kpiValue: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    fontWeight: 600,
    color: 'var(--text1)',
    fontVariantNumeric: 'tabular-nums',
    lineHeight: 1.1,
  },

  // Filter toolbar shared by the list-style views.
  filterRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 14,
    alignItems: 'flex-end',
    marginBottom: 14,
  },
  filterField: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  filterLabel: {
    fontSize: 10,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: 'var(--text3)',
    fontWeight: 700,
  },
  pillRow: {
    display: 'inline-flex',
    gap: 6,
  },
  pillBtn: {
    padding: '6px 12px',
    borderRadius: 999,
    border: '1px solid var(--border)',
    background: 'var(--bg2)',
    color: 'var(--text2)',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    letterSpacing: '0.02em',
    minHeight: 32,
  },
  pillBtnActive: {
    background: 'var(--text1)',
    color: '#fff',
    borderColor: 'var(--text1)',
  },
  dateInput: {
    height: 36,
    border: '1px solid var(--border)',
    borderRadius: 8,
    background: 'var(--bg2)',
    padding: '0 10px',
    fontSize: 13,
    color: 'var(--text1)',
    fontFamily: 'inherit',
    minWidth: 150,
  },

  // ─── Coming soon view ──────────────────────────────────────────────────
  comingShell: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
  },
  comingHead: {
    padding: '22px 32px 16px',
    borderBottom: '1px solid var(--border)',
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    flexShrink: 0,
  },
  comingBack: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '7px 12px 7px 8px',
    borderRadius: 8,
    background: 'var(--bg2)',
    color: 'var(--text1)',
    border: '1px solid var(--border)',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    fontFamily: 'inherit',
    minHeight: 38,
  },
  comingTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    fontWeight: 600,
    color: 'var(--text1)',
    margin: 0,
  },
  comingBody: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    padding: '48px 32px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    gap: 14,
  },
  comingHint: {
    fontSize: 14,
    color: 'var(--text2)',
    maxWidth: 460,
    lineHeight: 1.5,
  },
};
