// Shared styles for the Operations Hub modal and its child sub-flows.
// The hub modal sits at zIndex 70; child modals stack on top at 80.
// Same scrim colour as the rest of the terminal modals (RegisterPanel) so the
// transition between hub → child looks coherent.

const baseScrim: React.CSSProperties = {
  position: 'fixed',
  inset: 0,
  background: 'rgba(44,36,32,0.42)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  padding: 24,
};

export const hubStyles: Record<string, React.CSSProperties> = {
  scrim: { ...baseScrim, zIndex: 70 },
  childScrim: { ...baseScrim, zIndex: 80 },
  hubModal: {
    width: 720,
    maxWidth: '100%',
    background: 'var(--bg2)',
    borderRadius: 14,
    boxShadow: '0 24px 64px rgba(0,0,0,0.32)',
    border: '1px solid var(--border)',
    overflow: 'hidden',
  },
  childModal: {
    width: 540,
    maxWidth: '100%',
    background: 'var(--bg2)',
    borderRadius: 14,
    boxShadow: '0 24px 64px rgba(0,0,0,0.32)',
    border: '1px solid var(--border)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '92vh',
  },
  wideChildModal: {
    width: 760,
    maxWidth: '100%',
    background: 'var(--bg2)',
    borderRadius: 14,
    boxShadow: '0 24px 64px rgba(0,0,0,0.32)',
    border: '1px solid var(--border)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '92vh',
  },
  head: {
    padding: '22px 24px 16px',
    borderBottom: '1px solid var(--border)',
  },
  title: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    fontWeight: 600,
    color: 'var(--text1)',
    margin: 0,
  },
  sub: {
    fontSize: 13,
    color: 'var(--text2)',
    marginTop: 4,
    lineHeight: 1.45,
  },
  body: {
    padding: '20px 24px',
    overflowY: 'auto',
    flex: 1,
    minHeight: 0,
  },
  hubGrid: {
    padding: '20px 24px 24px',
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 12,
  },
  actions: {
    padding: '14px 22px 18px',
    borderTop: '1px solid var(--border)',
    display: 'flex',
    gap: 10,
    justifyContent: 'flex-end',
    background: 'var(--bg)',
  },
  cancelBtn: {
    padding: '11px 18px',
    borderRadius: 8,
    background: 'var(--bg2)',
    color: 'var(--text1)',
    fontSize: 13,
    fontWeight: 500,
    border: '1px solid var(--border)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    minHeight: 42,
    minWidth: 92,
  },
  primaryBtn: {
    padding: '11px 18px',
    borderRadius: 8,
    background: 'var(--text1)',
    color: '#fff',
    fontSize: 13,
    fontWeight: 600,
    border: '1px solid var(--text1)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    minHeight: 42,
    minWidth: 92,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  goldBtn: {
    padding: '11px 18px',
    borderRadius: 8,
    background: 'var(--gold)',
    color: '#2c2420',
    fontSize: 13,
    fontWeight: 600,
    border: '1px solid rgba(44,36,32,0.08)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    minHeight: 42,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    marginBottom: 14,
  },
  label: {
    fontSize: 11,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: 'var(--text3)',
    fontWeight: 600,
  },
  input: {
    height: 44,
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '0 12px',
    background: 'var(--bg)',
    color: 'var(--text1)',
    fontSize: 16,
    outline: 'none',
    fontFamily: "'Playfair Display', serif",
    fontVariantNumeric: 'tabular-nums',
  },
  select: {
    height: 44,
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '0 12px',
    background: 'var(--bg)',
    color: 'var(--text1)',
    fontSize: 14,
    outline: 'none',
    fontFamily: 'inherit',
  },
  textarea: {
    minHeight: 80,
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '10px 12px',
    background: 'var(--bg)',
    color: 'var(--text1)',
    fontSize: 14,
    outline: 'none',
    resize: 'vertical',
    fontFamily: 'inherit',
  },
  hint: {
    fontSize: 11,
    color: 'var(--text3)',
    fontStyle: 'italic',
  },
  errBanner: {
    marginTop: 12,
    padding: '8px 12px',
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 500,
    background: 'rgba(196,80,64,0.10)',
    color: 'var(--red)',
  },
  okBanner: {
    marginTop: 12,
    padding: '8px 12px',
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 500,
    background: 'rgba(74,140,92,0.10)',
    color: 'var(--green)',
  },
};
